### ISSUE TITLE
MagicMirror showing syntax error

### ISSUE THREAD

**Issue by VH-Tech** [pinsdorf/MMM-WeeklySchedule#1]
Hi ,
I followed all the instructions but I face a syntax error whenever I try to add MMM-WeeklySchedule to my config.js file.

My file with this module looks like this:
[git(1).txt](https://github.com/pinsdorf/MMM-WeeklySchedule/files/1863929/git.1.txt)

and when I remove the module this works pretty fine:
[git(2).txt](https://github.com/pinsdorf/MMM-WeeklySchedule/files/1863940/git.2.txt)

I'm a mere beginner please help me!!

**Comment by toasterlizard** [comment]
There was a } missing to close config: {

Try this:
[git1.txt](https://github.com/pinsdorf/MMM-WeeklySchedule/files/1929770/git1.txt)

**Comment by VH-Tech** [comment]
Thanks!! for your help.
I am closing the issue now.
