### ISSUE TITLE
Config showWeekdayinHeader: "false" still shows the weekday

### ISSUE THREAD

**Issue by pinsdorf** [pinsdorf/MMM-WeeklySchedule#4]
Mentioned by @Jacobphilli in issue #3 

Inputting...
showWeekdayinHeader: "false"
... still shows the weekday in the header. Am I doing something incorrect?

**Comment by pinsdorf** [comment]
I looked at the code and it looks good to me. @Jacobphilli, please try without quotation marks, because it is a boolean constant and not a string. 

`showWeekdayinHeader: false`

Can you please double-check?

**Comment by Jacobphilli** [comment]
Thanks for responding so quickly. And you are absolutely right, removing the quotations makes it work. That’s my mistake. Feel free to close this “issue”.
