### ISSUE TITLE
Danish Translation

### ISSUE THREAD

**Issue by SpyEye70** [pinsdorf/MMM-WeeklySchedule#5]
Hi
I am new to this Github thing, maybe this is the wrong way to go, but, I have made a danish translation to this module.
How am I going to share it with you ?

**Comment by pinsdorf** [comment]
Hi @SpyEye70! Thanks, your contribution is most welcome. The correct way to submit your changes is opening a pull request. See menu item _Pull request_ above.

The basic idea is as follows: 
1. You make a copy ("_fork_") of my repository in your GitHub user space.
2. Now, you own a copy of the code and change it at your will, i.e. add a new feature or correct a bug.
3. Once you are satisfied with changes in your repository you may want to contribute it back to my repository. For this reason you open a "PR" (pull request) in my repository. This way, you ask me to "pull changes from you".
4. When filling out the PR form you provide the URL of your GitHub repository and the tag/branch. 
5. After submitting the form people see see a public announcement of your pull request in my repository.
6. I, as owner of my repository, review your proposed code changes, may have suggestions, and finally accept the PR.
7. GitHub merges then your changes into my repository. 
8. Anybody else who has checked out the module from my repository will see that there are changes by you. Once these users update their local copies your changes get distributed one by one over the entire user-base.

Hope this gives you a first overview. GitHub has a documentation about ["creating a pull request from a fork"](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork) with examples and more details.

**Comment by pinsdorf** [comment]
@SpyEye70 kindly contributed a Danish translation with pull request #6. Thanks for your contribution!
